import { Grade } from '@/core/types';

// Starter word lists for each grade level
export const STARTER_WORD_LISTS: Record<Grade, string[]> = {
  PreK: [
    'I', 'A', 'THE', 'TO', 'AND', 'GO', 'YOU', 'DO', 'MY', 'SEE',
    'CAN', 'IT', 'IS', 'WE', 'ME', 'HE', 'BE', 'SHE', 'OR', 'ONE',
  ],
  K: [
    'AM', 'AT', 'ATE', 'ALL', 'ARE', 'BUT', 'CAN', 'COME', 'DID', 'DO',
    'FOR', 'GET', 'GOT', 'HAD', 'HAS', 'HER', 'HIM', 'HIS', 'IF', 'IN',
    'INTO', 'LIKE', 'LOOK', 'MAKE', 'NEW', 'NO', 'NOT', 'NOW', 'ON', 'ONE',
  ],
  '1': [
    'AFTER', 'AGAIN', 'AN', 'ANY', 'AS', 'ASK', 'BY', 'COULD', 'EVERY', 'FLY',
    'FROM', 'GIVE', 'GOING', 'HAD', 'HAS', 'HER', 'HIM', 'HIS', 'HOW', 'JUST',
    'KNOW', 'LET', 'LIVE', 'MAY', 'OF', 'OLD', 'ONCE', 'OPEN', 'OVER', 'PUT',
    'ROUND', 'SOME', 'STOP', 'TAKE', 'THANK', 'THEM', 'THEN', 'THINK', 'WALK', 'WERE',
  ],
  '2': [
    'ALWAYS', 'AROUND', 'BECAUSE', 'BEEN', 'BEFORE', 'BEST', 'BOTH', 'BUY', 'CALL', 'COLD',
    'DOES', 'DONT', 'FAST', 'FIRST', 'FIVE', 'FOUND', 'GAVE', 'GOES', 'GREEN', 'ITS',
    'MADE', 'MANY', 'OFF', 'OR', 'PULL', 'READ', 'RIGHT', 'SING', 'SIT', 'SLEEP',
    'TELL', 'THEIR', 'THESE', 'THOSE', 'UPON', 'US', 'USE', 'VERY', 'WASH', 'WHICH',
  ],
  '3': [
    'ABOUT', 'BETTER', 'BRING', 'CARRY', 'CLEAN', 'CUT', 'DONE', 'DRAW', 'DRINK', 'EIGHT',
    'FALL', 'FAR', 'FULL', 'GOT', 'GROW', 'HOLD', 'HOT', 'HURT', 'KIND', 'LAUGH',
    'LIGHT', 'LONG', 'MUCH', 'MYSELF', 'NEVER', 'ONLY', 'OWN', 'PICK', 'SEVEN', 'SHALL',
    'SHOW', 'SIX', 'SMALL', 'START', 'TEN', 'TODAY', 'TOGETHER', 'TRY', 'WARM', 'WISH',
  ],
  '4': [
    'ANSWER', 'APPLE', 'AWAY', 'BETWEEN', 'BOOK', 'BUILD', 'CHANGE', 'CITY', 'CLOSE', 'COUNTRY',
    'DIFFERENT', 'DOOR', 'EACH', 'EARLY', 'EARTH', 'END', 'ENOUGH', 'EXAMPLE', 'FAMILY', 'FATHER',
    'FOLLOW', 'FOOD', 'FORM', 'FOUR', 'FRIEND', 'GROUP', 'HAND', 'HEAD', 'HEAR', 'HIGH',
    'HOUSE', 'IDEA', 'IMPORTANT', 'KEEP', 'LARGE', 'LATE', 'LEARN', 'LETTER', 'LIFE', 'LISTEN',
  ],
  '5': [
    'ABOVE', 'ACROSS', 'AGAINST', 'ALONG', 'ALREADY', 'ALTHOUGH', 'AMONG', 'ANIMAL', 'ANOTHER', 'BECOME',
    'BEGIN', 'BEHIND', 'BELOW', 'BESIDE', 'BODY', 'BUSINESS', 'CERTAIN', 'CHILDREN', 'CHURCH', 'CLOSE',
    'COMMON', 'COMPLETE', 'COURSE', 'DEVELOP', 'DURING', 'EITHER', 'ENOUGH', 'ESPECIALLY', 'EVENING', 'EVERYTHING',
    'FATHER', 'FIELD', 'FIGURE', 'FORWARD', 'FRIEND', 'GOVERNMENT', 'HOWEVER', 'HUNDRED', 'INCREASE', 'LANGUAGE',
  ],
  '6': [
    'ABILITY', 'ACCEPT', 'ACCORDING', 'ACHIEVE', 'ACTION', 'ACTUALLY', 'ADDRESS', 'ADMINISTRATION', 'ADMIT', 'ADVANTAGE',
    'AFFECT', 'AFFORD', 'AGENCY', 'AGREEMENT', 'ALMOST', 'ALREADY', 'ALTERNATIVE', 'AMOUNT', 'ANALYSIS', 'ANCIENT',
    'APPEAR', 'APPROACH', 'APPROPRIATE', 'ARGUMENT', 'ARTICLE', 'ARTIST', 'ASSUME', 'ATTACK', 'ATTEMPT', 'ATTENTION',
    'ATTITUDE', 'AUDIENCE', 'AUTHORITY', 'AVAILABLE', 'AVERAGE', 'BALANCE', 'BEHAVIOR', 'BELIEF', 'BENEFIT', 'BOTTOM',
  ],
  '7': [
    'ABSOLUTELY', 'ACADEMIC', 'ACCEPTABLE', 'ACCOMPLISH', 'ACHIEVEMENT', 'ACKNOWLEDGE', 'ACQUISITION', 'ADEQUATE', 'ADMINISTRATIVE', 'ADOLESCENT',
    'ADVANTAGE', 'ADVOCACY', 'AESTHETIC', 'AGRICULTURE', 'ALGORITHM', 'ALTERNATIVE', 'AMBIGUOUS', 'AMENDMENT', 'ANALYSIS', 'ANNIVERSARY',
    'APPLICATION', 'APPROPRIATE', 'APPROXIMATE', 'ARCHITECTURE', 'ARRANGEMENT', 'ASSESSMENT', 'ASSIGNMENT', 'ASSISTANCE', 'ASSOCIATION', 'ASSUMPTION',
    'ATMOSPHERE', 'ATTITUDE', 'ATTRIBUTE', 'AUTHENTIC', 'AUTHORITY', 'AUTOMATION', 'AWARENESS', 'BACKGROUND', 'BENEFICIAL', 'BIOLOGICAL',
  ],
  '8': [
    'ABBREVIATION', 'ACCELERATION', 'ACCESSIBILITY', 'ACCOMMODATION', 'ACCOMPANIMENT', 'ACCOUNTABILITY', 'ACCUMULATION', 'ACHIEVEMENT', 'ACKNOWLEDGMENT', 'ADMINISTRATIVE',
    'ADVANTAGEOUS', 'ADVERTISEMENT', 'AFFECTIONATE', 'AGRICULTURAL', 'ALTERNATIVE', 'AMBASSADOR', 'AMENDMENT', 'AMPLIFICATION', 'ANALYTICAL', 'ANNIVERSARY',
    'ANTICIPATION', 'APOLOGETIC', 'APPARATUS', 'APPLICATION', 'APPRECIATION', 'APPRENTICESHIP', 'APPROPRIATE', 'APPROXIMATE', 'ARCHAEOLOGICAL', 'ARCHITECTURE',
    'ARRANGEMENT', 'ARTICULATION', 'ASTONISHMENT', 'ASTRONOMICAL', 'ATMOSPHERE', 'AUTHENTICATION', 'AUTHORIZATION', 'AUTOBIOGRAPHY', 'AVAILABILITY', 'BIBLIOGRAPHY',
  ],
};

// Get word list for a grade with optional custom words
export function getWordListForGrade(
  grade: Grade,
  customWords: string[] = []
): string[] {
  const starterWords = STARTER_WORD_LISTS[grade] || [];
  return [...starterWords, ...customWords];
}
